version: "3" 
services:
  web:
    build: .
    ports: 
      - "4000:4000"
    volumes:
      - .:/app
    command: mix phx.server
    depends_on:
      - db

  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db

